version: '3.8'

services:
  master:
    build:
      context: ./Master
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - replicated-log-network

  secondary1:
    build:
      context: ./Secondary
      dockerfile: Dockerfile
    environment:
      - PORT=5300
    ports:
      - "5300:5300"
    networks:
      - replicated-log-network

  secondary2:
    build:
      context: ./Secondary
      dockerfile: Dockerfile
    environment:
      - PORT=5301
    ports:
      - "5301:5301"
    networks:
      - replicated-log-network

networks:
  replicated-log-network:
    driver: bridge